title: AI Impulse
description: Mein Blog über KI und Technologie
baseurl: "/ai-impulse"
url: "https://promotos.github.io"

# markdown: kramdown
# highlighter: rouge
# theme: dinky
theme: minima

plugins:
  - jekyll-remote-theme

# Navigation
header_pages:
  - about.md
  - search.html
